#Hybrid Database Configuration (SQLITE Embedded / POSTGRESQL Network)
#Tue Aug 18 01:35:07 CET 2026
db.host=localhost
db.name=Employee_Managment
db.password=2005
db.port=5432
db.sqlite.path=database.db
db.type=SQLITE
db.user=postgres
