#Hybrid Database Configuration (SQLITE Embedded / POSTGRESQL Network)
#Mon Aug 17 03:41:22 CET 2026
db.host=localhost
db.name=Employee_Managment
db.password=2005
db.port=5432
db.sqlite.path=database.db
db.type=SQLITE
db.user=postgres
